### ISSUE TITLE
Authentication does not work as in example

### ISSUE THREAD

**Issue by kruckerr** [zandero/rest.vertx#106] opened 2021-03-04 12:59 UTC
Hi

I tried the newest version (1.0.4) with Vert.x 4.0.2. But I have problems with the authorization. We are working with JWT tokens.

First I migrated to the new version without changing my code. When I call a REST path annotated with `@RolesAllowed("Admin")`, I get a 403 (Forbidden) response event though the token contains the "Admin" permission. Before the upgrade, this worked fine.
```java
@Path("/private")
public class PrivateHelloRestController implements IRestController {
    private static final Logger LOGGER = LoggerFactory.getLogger(PrivateHelloRestController.class);

    @GET
    @Path("/hello")
    @Produces(MediaType.APPLICATION_JSON)
    @RolesAllowed({"Admin"})
    public String hello(@Context User user) {
        LOGGER.debug("This is the user: {}", user.principal());
        return "Private hello from Vert.x";
    }
}
```

Then I tried to migrate to then new authentication and authorization approach. When I added my authentication provider as a global authentication provider, it works fine. 
```java
        RestRouter.authenticateWith(MyAuthenticator.class);
```
and
```java
@Path("/private")
public class PrivateHelloRestController implements IRestController {
    private static final Logger LOGGER = LoggerFactory.getLogger(PrivateHelloRestController.class);

    @GET
    @Path("/hello")
    @Produces(MediaType.APPLICATION_JSON)
    @Authorize(MyAuthorizationProvider.class)
    public String hello(@Context User user) {
        LOGGER.debug("This is the user: {}", user.principal());
        return "Private hello from Vert.x";
    }
}
```

But we have some paths, that must be accessable without authorization. So a global authentication is no option. When I annotate a class with `@Authenticate` as in your example, my custom authenticator implementation is never called. 
```java
@Path("/private")
@Authenticate(MyAuthenticator.class)
public class PrivateHelloRestController implements IRestController {
    private static final Logger LOGGER = LoggerFactory.getLogger(PrivateHelloRestController.class);

    @GET
    @Path("/hello")
    @Produces(MediaType.APPLICATION_JSON)
    @Authorize(MyAuthorizationProvider.class)
    public String hello(@Context User user) {
        LOGGER.debug("This is the user: {}", user.principal());
        return "Private hello from Vert.x";
    }
}
```

I works, when I put the annotation to a method. 
```java
@Path("/private")
public class PrivateHelloRestController implements IRestController {
    private static final Logger LOGGER = LoggerFactory.getLogger(PrivateHelloRestController.class);

    @GET
    @Path("/hello")
    @Produces(MediaType.APPLICATION_JSON)
    @Authenticate(MyAuthenticator.class)
    @Authorize(MyAuthorizationProvider.class)
    public String hello(@Context User user) {
        LOGGER.debug("This is the user: {}", user.principal());
        return "Private hello from Vert.x";
    }
}
```

**Comment by drejc** [comment] 2021-03-04 13:18
Hard to tell only from the REST enpoints .. but the new Authorize/Authenticate dance is always as follows

The RestAuthenticationProvider must read the Credentials ... aka headers in request or similar
Those Credentials are then handed over to the authenticate method where a User entity must be generated as a result

The Authorization provider then takes this User entity and checks if User is in correct Role ... 
The User implementation must match the Role check (some are already provided by vert.x 4, or you can simply implement your own) ... note that the User must provide the correct list of Auhtorizatoins, see this simple example:

```java
/**
 * Simplistic user where name is his role ...
 */
public class SimulatedUser extends UserImpl {

    private final String role;

    public SimulatedUser(String role) {
        this.role = role;
    }

    public String getRole() {
        return role;
    }

    @Override
    public Authorizations authorizations() { // IMPORTANT ... must provide what you authorize against
        return new AuthorizationsImpl().add("",
                                            RoleBasedAuthorization.create(role))
                   .add(TestAuthorizationProvider.ID,
                        PermissionBasedAuthorization.create(role));
    }

    public static SimulatedUser valueOf(String value) {
        return new SimulatedUser(value);
    }
}
```

If you get a  403 (Forbidden) then apperently the Authentication was successfull / you were able to provide the User enitity ... 
so the problem is in the Authorization where the User role is not matched.

I suggest that you debug the getAuthorizations method in AuthorizationProvider ... why you User role is not matched

PS: You can assign a Role directly to the @Auhorize annotation ... 
`@Authorize(value= MyAuthorizationProvider.class, role = "user")`

```java
@Override
    public void getAuthorizations(User user, Handler<AsyncResult<Void>> handler) {
        if (PermissionBasedAuthorization.create("HasPermission").match(user)) {
            handler.handle(Future.succeededFuture());
        } else {
            handler.handle(Future.failedFuture("You are not allowed in!"));
        }
    }

```

So both the **User** and the **AuthorizationProvider** must match with the same _Authorization_ ... 
in the given example it is the: **PermissionBasedAuthorization** ... but you can use a different implementation.

**Comment by kruckerr** [comment] 2021-03-04 14:50
OK. Now I understand. In my case, the User is created by the `io.vertx.ext.auth.jwt.JWTAuth` when I authenticate with my JWT token. This user has the PermissionBasedAuthorization. The default authorization provider is `com.zandero.rest.authorization.RoleBasedUserAuthorizationProvider`. So it will never match. Is there a possibility to override the default authorization provider or do I have to define it for each method with the `@Authorize` annotation?

My second question was, why the `@Authenticate` annotation on the class has no effect. I have to annotate the authenticator on each method as well.

**Comment by drejc** [comment] 2021-03-04 16:16
The RoleBasedAuthorizationProvider is the default provider assigned it should be overriden by the provider given in the @Authorize method/class. The @Authenticate should also work for both class and method annotations. Will take a second look, but to my knowledge I have some test with both options and all work fine.

**Comment by kruckerr** [comment] 2021-03-04 16:47
Shouldn't it take the authentication and authorization provider from base when call the RouteDefinition constructor for a method.
```java
public RouteDefinition(RouteDefinition base, Method classMethod) {

        // copy base route
        if (base.getApplicationPath() != null) {
            applicationPath(base.getApplicationPath());
        }

        path(base.getPath());

        consumes = base.getConsumes();
        produces = base.getProduces();
        method = base.getMethod();

        reader = base.getReader();
        writer = base.getWriter();
        contextProvider = base.getContextProvider();

        // set root privileges
        permitAll = base.getPermitAll();
        roles = base.roles;

        if (roles != null) {
            permitAll = null;
        }

        exceptionHandlers = ArrayUtils.join(exceptionHandlers, base.exceptionHandlers);

        // complement / override with additional annotations
        init(classMethod.getAnnotations());

        List<MethodParameter> pathParams = PathConverter.extract(path);
        params = join(params, pathParams);

        setArguments(classMethod);
        evaluatePath();
    }
```

**Comment by drejc** [comment] 2021-03-04 17:58
You are correct ... somehow I missed that ... nice catch ... will release a new version

**Closed** 2021-03-04 19:09 UTC

**Comment by drejc** [comment] 2021-03-04 19:49
1.0.5 version is published, 
I have also improved the RouteDefinition log / print out - so you should see the assigned Authorization/Authentication of each route: 

```
INFO  com.zandero.rest.RestRouter - Registering route:        GET /private/fourthAccess                                        @Authenticate[MyOtherAuthenticator]                @Authorize[OtherAuthorizationProvider]             
INFO  com.zandero.rest.RestRouter - Registering route:        GET /private/access                                              @Authenticate[MySimpleAuthenticator]               @Authorize[TestAuthorizationProvider]              
INFO  com.zandero.rest.RestRouter - Registering route:        GET /private/secondAccess                                        @Authenticate[MyOtherAuthenticator]                @Authorize[TestAuthorizationProvider]              
INFO  com.zandero.rest.RestRouter - Registering route:        GET /private/thirdAccess                                         @Authenticate[MySimpleAuthenticator]               @Authorize[OtherAuthorizationProvider] 
```

**Comment by kruckerr** [comment] 2021-03-05 06:03
Now it works fine. Thank you for your fast help.

**Comment by drejc** [comment] 2021-03-05 08:13
👍
