### ISSUE TITLE
When Using custom annotation, it occurs java.lang.IllegalArgumentException: Missing or empty route '@Path'!

### ISSUE THREAD

**Issue by shuitai** [zandero/rest.vertx#56] opened 2020-03-10 14:10 UTC
Exception in thread "main" java.lang.IllegalArgumentException: Missing or empty route '@Path'!
at com.zandero.utils.Assert.isFalse(Assert.java:38) at com.zandero.utils.Assert.notNullOrEmptyTrimmed(Assert.java:89) at com.zandero.rest.data.RouteDefinition.path(RouteDefinition.java:487) at com.zandero.rest.data.RouteDefinition.join(RouteDefinition.java:252) at com.zandero.rest.AnnotationProcessor.join(AnnotationProcessor.java:120) at com.zandero.rest.AnnotationProcessor.collect(AnnotationProcessor.java:101) at com.zandero.rest.AnnotationProcessor.get(AnnotationProcessor.java:43) at com.zandero.rest.RestRouter.register(RestRouter.java:124) at com.zandero.rest.RestRouter.register(RestRouter.java:82) at com.zandero.rest.RestBuilder.getRouter(RestBuilder.java:410) at com.zandero.rest.RestBuilder.build(RestBuilder.java:452) at com.vertx.example.BootStrap.main(BootStrap.java:36)

please check https://github.com/shuitai/vertx-rest-example/blob/master/src/main/java/com/vertx/example/api/TestRest2.java

**Comment by drejc** [comment] 2020-03-11 07:29
This is most probably a duplicate of #55

**Comment by drejc** [comment] 2020-03-13 07:37
Confirmed duplicate of #55

**Closed by drejc** 2020-03-13 07:37 UTC
Labels: duplicate
